name: Build and Push Secrets Image

on:
  push:
    branches:
      - "main"
      - "develop/*"
    paths:
      - 'src/**'
      - 'Dockerfile'
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1 # set this to your preferred AWS region, e.g. us-west-1

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@master
      with:
        platforms: linux/amd64, linux/arm64

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.ASSUME_ROLE }}
        role-duration-seconds: 900
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Login to GitHub Container Registry
      id: login-ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: aws-lambda-secrets-extension
      with:
        images: |
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
          ghcr.io/${{ github.repository }}

    - name: Build and Push Image
      id: build-and-push
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest
        labels: ${{ steps.meta.outputs.labels }}
