name: Go

on:
  push:
    tags: "releases/[1-9]+.[0-9]+.[0-9]+"
    branches: [ "main" ]
    # paths:
    #   - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      working-directory: src
      run: go build -v ./...

    # - name: Test
    #   run: go test -v src/...

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: lambda-secrets
        # A file, directory or wildcard pattern that describes what to upload
        path: src/lambda-secrets

    - name: Create Release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags/releases/') && github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: "Lambda Secrets Release Build"
        body: "Lamda Secrets Release Build from ${{ github.ref }}/${{ github.sha }}"
        draft: true
        prerelease: true