name: Publish Lambda Secrets Layer
on:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  LAMBDA_SECRETS_LAYER: 'aws-lambda-secrets'

permissions:
  contents: read

jobs:
  deploy-secrets-layer:
    name: Publish Secrets Layer Version
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 900

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Go Script
        # working-directory: src/
        run: |
          go version
          go mod verify
          go mod tidy
          go build -o ./fetch-secrets ./cmd/fetch-secrets/main.go
          go build -o ./load-secrets ./cmd/load-secrets/main.go

      - name: Zip Function Artifacts
        env:
          release_id: ${{ format('lambda-secrets-layer-{0}.zip', github.head_ref )}}
        run: |
          mkdir ./extensions
          cp ./fetch-secrets ./extensions
          mkdir ./extensions/wrapper
          cp ./load-secrets ./extensions/wrapper
          zip -r ./lambda-secrets-$release_id.zip ./extensions

      - name: Update Lambda Function Code
        env:
          release_id: ${{ format('lambda-secrets-layer-{0}.zip', github.head_ref )}}
        run: |
          aws lambda publish-layer-version --layer-name "${LAMBDA_SECRETS_LAYER}" --zip-file fileb://lambda-secrets-$release_id.zip  --compatible-runtimes python3.9 python3.8 ruby2.5 --compatible-architectures x86_64
          rm -r ./extensions
