name: Publish Lambda Secrets Layer
on:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  LAMBDA_SECRETS_LAYER: 'aws-lambda-secrets-layer'

permissions:
  contents: read

jobs:
  publish-secrets-layer:
    name: Publish Secrets Layer Version
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 900

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cross Complile Go Scripts and Generate ZIP archives
        # working-directory: src/
        run: |
          make release

      - name: Update Lambda Layer Version
        # env:
        #   release_id: ${{ format('aws-lambda-secrets-{0}.zip', github.head_ref )}}
        run: |
          aws lambda publish-layer-version --layer-name "${LAMBDA_SECRETS_LAYER}-x86_64" --zip-file fileb://aws-lambda-secrets-amd64.zip  --compatible-runtimes python3.9 python3.8 ruby2.5 --compatible-architectures x86_64
          aws lambda publish-layer-version --layer-name "${LAMBDA_SECRETS_LAYER}-arm64" --zip-file fileb://aws-lambda-secrets-arm64.zip  --compatible-runtimes python3.9 python3.8 ruby2.5 --compatible-architectures arm64
          rm aws-lambda-secrets-amd64.zip aws-lambda-secrets-arm64.zip
